#include "signatures.hpp"

#include <windows.h>

#include <cstring>
#include <vector>

namespace cw {

// Generated by tools/make_signatures.py from the 2013-07-20 build and confirmed
// to match exactly once in the 2013-07-02 build as well.
const char kSigWorldMapGetCell[] =
    "55 8B EC 53 56 8B 75 08 57 8B D9 85 F6 78 69 8B 7D 0C 85 FF 78 62 81 FE 00 00 01 00 "
    "7D 5A 81 FF 00 00 01 00 7D 52 8B C6 99 83 E2 3F 8D 0C 02 8B C7 99 83 E2 3F C1 F9 06 "
    "03 C2 C1 F8 06 C1 E1 0A";

const char kSigMapOverlayDraw[] =
    "55 8B EC 6A FF 68 ?? ?? ?? ?? 64 A1 00 00 00 00 50 81 EC 88 04 00 00 A1 ?? ?? ?? ?? "
    "33 C5 89 45 F0 53 56 57 50 8D 45 F4 64 A3 00 00 00 00 8B D9 89 9D A0 FC FF FF C7 85 "
    "7C FC FF FF 00 00 00 00";

namespace {

struct Token {
    std::uint8_t value;
    bool wildcard;
};

std::vector<Token> parse(const char* pattern) {
    std::vector<Token> out;
    for (const char* p = pattern; *p;) {
        if (*p == ' ') {
            ++p;
            continue;
        }
        if (p[0] == '?') {
            out.push_back({0, true});
            p += (p[1] == '?') ? 2 : 1;
            continue;
        }
        auto nibble = [](char c) -> int {
            if (c >= '0' && c <= '9') return c - '0';
            if (c >= 'A' && c <= 'F') return c - 'A' + 10;
            if (c >= 'a' && c <= 'f') return c - 'a' + 10;
            return -1;
        };
        const int hi = nibble(p[0]);
        const int lo = nibble(p[1]);
        if (hi < 0 || lo < 0) return {};
        out.push_back({static_cast<std::uint8_t>(hi * 16 + lo), false});
        p += 2;
    }
    return out;
}

}  // namespace

bool module_text(ModuleRange* out) {
    auto* base = reinterpret_cast<std::uint8_t*>(GetModuleHandleW(nullptr));
    if (!base) return false;

    const auto* dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(base);
    if (dos->e_magic != IMAGE_DOS_SIGNATURE) return false;

    const auto* nt = reinterpret_cast<const IMAGE_NT_HEADERS32*>(base + dos->e_lfanew);
    if (nt->Signature != IMAGE_NT_SIGNATURE) return false;

    const auto* section = IMAGE_FIRST_SECTION(nt);
    for (unsigned i = 0; i < nt->FileHeader.NumberOfSections; ++i, ++section) {
        if (std::memcmp(section->Name, ".text", 5) == 0) {
            out->text_begin = base + section->VirtualAddress;
            out->text_end = out->text_begin + section->Misc.VirtualSize;
            return true;
        }
    }
    return false;
}

std::uint8_t* find_unique(const ModuleRange& range, const char* pattern) {
    const std::vector<Token> tokens = parse(pattern);
    if (tokens.empty()) return nullptr;

    std::uint8_t* found = nullptr;
    const std::size_t span = tokens.size();
    if (static_cast<std::size_t>(range.text_end - range.text_begin) < span) return nullptr;

    for (std::uint8_t* at = range.text_begin; at <= range.text_end - span; ++at) {
        std::size_t i = 0;
        for (; i < span; ++i) {
            if (!tokens[i].wildcard && at[i] != tokens[i].value) break;
        }
        if (i != span) continue;
        if (found) return nullptr;  // ambiguous: refuse rather than guess
        found = at;
    }
    return found;
}

}  // namespace cw
